### ISSUE TITLE
How to solve this problem

### ISSUE THREAD

**Issue by TWJ718925** [sommerschield/ancient-text-restoration#12]
Is it because of data processing that leads to 'ascii' codec can't encode characters, or is it the python version? Eventually, the loss will appear as ‘nan’.

2020-05-31 10:25:19 cfc17c86ba01 train.py[5702] INFO 0: train: 5.10463142, train_avg: 5.10463142
2020-05-31 10:28:05 cfc17c86ba01 train.py[5702] INFO 20: train: 5.10399675, train_avg: 5.10408317
2020-05-31 10:30:26 cfc17c86ba01 train.py[5702] INFO 40: train: 5.10304451, train_avg: 5.10375757
2020-05-31 10:32:49 cfc17c86ba01 train.py[5702] INFO 60: train: 5.10306835, train_avg: 5.10355185
2020-05-31 10:35:01 cfc17c86ba01 train.py[5702] INFO 80: train: 5.10499716, train_avg: 5.10371275
--- Logging error ---
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/logging/__init__.py", line 996, in emit
    stream.write(msg)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 134-137: ordinal not in range(128)
Call stack:
  File "<string>", line 1, in <module>
  File "/home/ancient-text-restoration-master/pythia/train.py", line 194, in main
    y_, y_pred_, x_)
Message: '%d: train: %.8f, train_avg: %.8f, valid_cer: %.3f, valid_cer_avg: %.3f, y: %s, y_pred: %s, x: %s'
Arguments: (100, 5.1027946, 5.103714559984167, 0.9999996, 0.9999996, 'ϊνος', 'ῠῴῴῴῂῂᾲᾲᾲᾠ', 'ντι λά____ τύμβῳ παρέστην τὸν τεθνηκότ ἐννέπω ὄνομα ----λ-- φιλήμονος πατρός ἐτῶν δὲ τρειῶν ἄωρος ἐγλείπει βίον. τῆς μητρὸς αὐτοῦ ὄνομα σημαίνω πάλιν ἀριστονείκη ἥτις ὤδεινεν μάτην')
2020-05-31 10:38:15 cfc17c86ba01 train.py[5702] INFO 100: train: 5.10279465, train_avg: 5.10371456, valid_cer: 1.000, valid_cer_avg: 1.000, y: ϊνος, y_pred: ῠῴῴῴῂῂᾲᾲᾲᾠ, x: ντι λά____ τύμβῳ παρέστην τὸν τεθνηκότ ἐννέπω ὄνομα ----λ-- φιλήμονος πατρός ἐτῶν δὲ τρειῶν ἄωρος ἐγλείπει βίον. τῆς μητρὸς αὐτοῦ ὄνομα σημαίνω πάλιν ἀριστονείκη ἥτις ὤδεινεν μάτην
2020-05-31 10:38:15 cfc17c86ba01 train.py[5702] INFO Best model with cer 1.000. Saving to /home/ancient-text-restoration-master/tf/checkpoint//model_biword_epigraphy_2020_05_31 10:24/
2020-05-31 10:40:20 cfc17c86ba01 train.py[5702] INFO 120: train: nan, train_avg: nan
2020-05-31 10:42:15 cfc17c86ba01 train.py[5702] INFO 140: train: nan, train_avg: nan

**Comment by TWJ718925** [comment]
Why is y-pred empty when iterating to a certain number of times, is it because of the data set? Then the loss is nan.

νε, y_pred: , x: αι ὃν ἔκτ___ νοῦσος ἀμειδὴς καὶ νέον εἰς ἀΐδην ἤγαγεν αἰνόμορον εἴκοσι καὶ δύ ἔτη ζωῆς βίον ἐξανύσαντα σωφροσύνην αἰεὶ πᾶσ
2020-06-01 07:10:57 2917dcda5992 train.py[740] INFO 320: train: 3.89014983, train_avg: 4.17952140
2020-06-01 07:13:15 2917dcda5992 train.py[740] INFO 340: train: 4.03862715, train_avg: 4.03505693
2020-06-01 07:15:14 2917dcda5992 train.py[740] INFO 360: train: 4.05098963, train_avg: 4.05917709
2020-06-01 07:17:32 2917dcda5992 train.py[740] INFO 380: train: 3.50972223, train_avg: 3.89622156
2020-06-01 07:20:17 2917dcda5992 train.py[740] INFO 400: train: 4.63122225, train_avg: 3.95952514, valid_cer: 1.000, valid_cer_avg: 1.000, y: ευσει, y_pred: , x: ντ --- -----ς ἐλ_____νίου 0 πρυτανείας οἱ πρυτάνεις τῆς ἀντιοχίδος φυλῆς τιμήσαντες ἑαυτοὺς καὶ τοὺς ἀισίτους ἀνέγραψαν ἐπώνυμος φλ σωσιγένης παλληνεύς παλληνεῖς --- ις --- ἀσκληπιάδου --- ἀσκληπιάδου --- προσδοκίμου ----- ο - καὶ ἅβρων ----- του --- τροφίμου ἀναφλύστιοι αἴλ μᾶρκος ἀθήναιος λεωνίδης ἀθηναίου διονυσόδωρος ζωσίμου λεωνίδης φλώρου ἀφροδίσιος αἴλ δίων ἐργύδαι
2020-06-01 07:22:20 2917dcda5992 train.py[740] INFO 420: train: nan, train_avg: nan
2020-06-01 07:24:28 2917dcda5992 train.py[740] INFO 440: train: nan, train_avg: nan
2020-06-01 07:26:56 2917dcda5992 train.py[740] INFO 460: train: nan, train_avg: nan
2020-06-01 07:29:06 2917dcda5992 train.py[740] INFO 480: train: nan, train_avg: nan
2020-06-01 07:31:53 2917dcda5992 train.py[740] INFO 500: train: nan, train_avg: nan, valid_cer: 1.000, valid_cer_avg: 1.000, y: δολα κα, y_pred: , x: ος ἐγραμμάτευε ἔδοχσεν τει βολει καὶ τοι δέμοι ἀκαμαντὶς ἐπρυτάνευε χαρίας ἐγραμμάτευε τιμόχσενος ἐπεστάτε καλλί ας εἶπε χσυμμαχίαν εἶναι ἀθεναίοις καὶ ῥεγίνοις τὸν δὲ ὅρκον ὀμοσάντον ἀθεναῖοι ἵνα ε ι τὰ πάντα πιστὰ καὶ ἄ_______ὶ ἁπλᾶ παρ ἀθεναίον ἐς ἀίδιον ῥεγίνοις κατὰ τάδε ὀμνύντες χσύμμαχ

**Comment by iassael** [comment]
Hi @TWJ718925, y_pred can be empty until the model learns to count the number of underscores in the input text and outputs an end of sentence character. Regarding the UnicodeEncodeError you are receiving this might have to do with your python distribution (we are using anaconda) or your locale settings.

I double checked again and I'm not receiving any nan errors even with the third-party uploaded dataset.

Finally, this is an open-source project aiming to help the community, since the error is not reproducable in our setup it's really difficult to help you. When you identify the problem please send us a pull request with your findings. Thank you for your feedback!
